# Generated by Django 4.2.5 on 2023-09-28 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("haberler", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="makale",
            old_name="yayinlanma_tarihi",
            new_name="yayimlanma_tarihi",
        ),
    ]
