# Generated by Django 4.2.5 on 2023-09-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitaplar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yorum",
            name="yorum",
            field=models.TextField(blank=True, null=True),
        ),
    ]
