# Generated by Django 4.2.5 on 2023-09-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(max_length=250)),
            ],
            options={
                "verbose_name": "Yazar",
                "verbose_name_plural": "Yazarlar",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="isim")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="açıklama"),
                ),
                ("price", models.FloatField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("activate", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kitap",
                "verbose_name_plural": "Kitaplar",
            },
        ),
    ]
